openapi: 3.0.3
info:
  title: Swagger HIP Facade - OpenAPI 3.0
  description: |-
    This is a sample HIP Initiated Linking Client based on the OpenAPI 3.0 specification
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /add-patients:
    put:
      tags:
        - patients
      summary: Insert or Update a list of patients
      description: Insert or Update a list of patients
      operationId: upsertPatients
      requestBody:
        description: Insert or update a list of patients in the wrapper database
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Patient'
        required: true
      responses:
        '200':
          description: Successfully added patients
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Patient not found
        '422':
          description: Validation exception


components:
  schemas:
    Patient:
      type: object
      properties:
        abhaAddress:
          type: string
        name:
          type: string
        gender:
          type: string
          example: M
        dateOfBirth:
          type: string
          example: '2003-09-23'
        patientReference:
          type: string
        patientDisplay:
          type: string
        patientMobile:
          type: string