version: '3.8'

services:
  gateway:
    build:
      context: mock-gateway
      dockerfile: ./Dockerfile
    image: gateway
    ports:
    - '8090:8090'
    networks:
    - docker_network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
    - '27017:27017'
    volumes:
    - mongodb_vol:/data/db
    networks:
    - docker_network

  abdm-wrapper:
    build: .
    image: abdm-wrapper
    ports:
    - '8082:8082'
    depends_on:
    - gateway
    - mongodb
    networks:
    - docker_network

volumes:
  mongodb_vol:

networks:
  docker_network:
    driver: bridge