version: '3.8'

services:
  abdm-wrapper:
    build: .
    image: abdm-wrapper
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - docker_network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_vol:/data/db
    networks:
      - docker_network

volumes:
  mongodb_vol:

networks:
  docker_network:
    driver: bridge