openapi: 3.0.3
info:
  description: This is a sample HIP Initiated Linking Client based on the OpenAPI
    3.0 specification
  title: Swagger HIP Facade - OpenAPI 3.0
  version: 1.0.0
servers:
- url: http://localhost:8080/v1
paths:
  /add-patients:
    put:
      description: Insert or Update a list of patients
      operationId: upsertPatients
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Patient'
              type: array
        description: Insert or update a list of patients in the wrapper database
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Successfully added patients
        "400":
          description: Invalid ID supplied
        "404":
          description: Patient not found
        "422":
          description: Validation exception
      summary: Insert or Update a list of patients
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
components:
  schemas:
    Patient:
      example:
        patientMobile: patientMobile
        gender: M
        patientReference: patientReference
        name: name
        dateOfBirth: 2003-09-23
        patientDisplay: patientDisplay
        abhaAddress: abhaAddress
      properties:
        abhaAddress:
          type: string
        name:
          type: string
        gender:
          example: M
          type: string
        dateOfBirth:
          example: 2003-09-23
          type: string
        patientReference:
          type: string
        patientDisplay:
          type: string
        patientMobile:
          type: string
      type: object

